services:
#postgres ultra basico
  postgres:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: contraBD
    ports:
      - 3004:5432
#pgadmin4
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: contraManejador
    ports:
      - 3005:80
    depends_on:
      - postgres
