services:
#postgres ultra basico
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
#administrador web multiproposito
  adminer: 
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - postgres
#clasico de postgres, que se supene que ya hay nueva version
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 80:80
    depends_on:
      - postgres
  