services:
#postgres ultra basico
  postgres:
    image: postgres:9.5
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 3004:5432
#administrador web multiproposito
  # adminer: 
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - postgres
#clasico de postgres, que se supone que ya hay nueva version
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - 3005:80
    # depends_on:
    #   - postgres
  