version: '3.3'
services:
  anaconda3:
    ports:
      - '8888:8888'
    image: continuumio/anaconda3
    command: /bin/bash -c "conda install jupyter -y --quiet && mkdir -p /opt/notebooks && jupyter notebook --notebook-dir=/opt/notebooks --ip='*' --port=8888 -0-no-browser --allow-root"
    tty: true